import db from "..";
import { advocates } from "../schema";

export const specialties = [
  {label: "Bipolar", value: "bipolar"},
  {label: "LGBTQ", value: "lgbtq"},
  {label: "Medication/Prescribing", value: "medication-prescribing"},
  {label: "Suicide History/Attempts", value: "suicide-history-attempts"},
  {label: "General Mental Health (anxiety, depression, stress, grief, life transitions)", value: "general-mental-health"},
  {label: "Men's issues", value: "men's-issues"},
  {label: "Relationship Issues (family, friends, couple, etc)", value: "relationship-issues"},
  {label: "Trauma & PTSD", value: "trauma-and-ptsd"},
  {label: "Personality disorders", value: "personality-disorders"},
  {label: "Personal growth", value: "personal-growth"},
  {label: "Substance use/abuse", value: "substance-use-abuse"},
  {label: "Pediatrics", value: "pediatrics"},
  {label: "Women's issues (post-partum, infertility, family planning)", value: "women's-issues-post-partum-infertility-family-planning"},
  {label: "Chronic pain", value: "chronic-pain"},
  {label: "Weight loss & nutrition", value: "weight-loss-and-nutrition"},
  {label: "Eating disorders", value: "eating-disorders"},
  {label: "Diabetic Diet and nutrition", value: "diabetic-diet-and-nutrition"},
  {label: "Coaching (leadership, career, academic and wellness)", value: "coaching"},
  {label: "Life coaching", value: "life-coaching"},
  {label: "Obsessive-compulsive disorders", value: "obsessive-compulsive-disorders"},
  {label: "Neuropsychological evaluations & testing (ADHD testing)", value: "neuropsychological-evaluations-and-testing-adhd-testing"},
  {label: "Attention and Hyperactivity (ADHD)", value: "attention-and-hyperactivity-adhd"},
  {label: "Sleep issues", value: "sleep-issues"},
  {label: "Schizophrenia and psychotic disorders", value: "schizophrenia-and-psychotic-disorders"},
  {label: "Learning disorders", value: "learning-disorders"}, 
  {label: "Domestic abuse", value: "domestic-abuse"},
];

export const cities = [
  {label: "New York", value: "new-york"},
  {label: "Los Angeles", value: "los-angeles"},
  {label: "Chicago", value: "chicago"},
  {label: "Houston", value: "houston"},
  {label: "Phoenix", value: "phoenix"},
  {label: "Philadelphia", value: "philadelphia"},
  {label: "San Antonio", value: "san-antonio"},
  {label: "San Diego", value: "san-diego"},
  {label: "Dallas", value: "dallas"},
  {label: "San Jose", value: "san-jose"},
];

const randomSpecialty = () => {
  const random1 = Math.floor(Math.random() * 24);
  const random2 = Math.floor(Math.random() * (24 - random1)) + random1 + 1;

  return [random1, random2];
};

const advocateData = [
  {
    firstName: "John",
    lastName: "Doe",
    city: "New York",
    degree: "MD",
    specialties: specialties.map(s => s.value).slice(...randomSpecialty()),
    yearsOfExperience: 10,
    phoneNumber: "5551234567",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    city: "Los Angeles",
    degree: "PhD",
    specialties: specialties.map(s => s.value).slice(...randomSpecialty()),
    yearsOfExperience: 8,
    phoneNumber: "5559876543",
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    city: "Chicago",
    degree: "MSW",
    specialties: specialties.map(s => s.value).slice(...randomSpecialty()),
    yearsOfExperience: 5,
    phoneNumber: "5554567890",
  },
  {
    firstName: "Michael",
    lastName: "Brown",
    city: "Houston",
    degree: "MD",
    specialties: specialties.map(s => s.value).slice(...randomSpecialty()),
    yearsOfExperience: 12,
    phoneNumber: "5556543210",
  },
  {
    firstName: "Emily",
    lastName: "Davis",
    city: "Phoenix",
    degree: "PhD",
    specialties: specialties.map(s => s.value).slice(...randomSpecialty()),
    yearsOfExperience: 7,
    phoneNumber: "5553210987",
  },
  {
    firstName: "Chris",
    lastName: "Martinez",
    city: "Philadelphia",
    degree: "MSW",
    specialties: specialties.map(s => s.value).slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: "5557890123",
  },
  {
    firstName: "Jessica",
    lastName: "Taylor",
    city: "San Antonio",
    degree: "MD",
    specialties: specialties.map(s => s.value).slice(...randomSpecialty()),
    yearsOfExperience: 11,
    phoneNumber: "5554561234",
  },
  {
    firstName: "David",
    lastName: "Harris",
    city: "San Diego",
    degree: "PhD",
    specialties: specialties.map(s => s.value).slice(...randomSpecialty()),
    yearsOfExperience: 6,
    phoneNumber: "5557896543",
  },
  {
    firstName: "Laura",
    lastName: "Clark",
    city: "Dallas",
    degree: "MSW",
    specialties: specialties.map(s => s.value).slice(...randomSpecialty()),
    yearsOfExperience: 4,
    phoneNumber: "5550123456",
  },
  {
    firstName: "Daniel",
    lastName: "Lewis",
    city: "San Jose",
    degree: "MD",
    specialties: specialties.map(s => s.value).slice(...randomSpecialty()),
    yearsOfExperience: 13,
    phoneNumber: "5553217654",
  },
  {
    firstName: "Sarah",
    lastName: "Lee",
    city: "Austin",
    degree: "PhD",
    specialties: specialties.map(s => s.value).slice(...randomSpecialty()),
    yearsOfExperience: 10,
    phoneNumber: "5551238765",
  },
  {
    firstName: "James",
    lastName: "King",
    city: "Jacksonville",
    degree: "MSW",
    specialties: specialties.map(s => s.value).slice(...randomSpecialty()),
    yearsOfExperience: 5,
    phoneNumber: "5556540987",
  },
  {
    firstName: "Megan",
    lastName: "Green",
    city: "San Francisco",
    degree: "MD",
      specialties: specialties.map(s => s.value).slice(...randomSpecialty()),
    yearsOfExperience: 14,
    phoneNumber: "5559873456",
  },
  {
    firstName: "Joshua",
    lastName: "Walker",
    city: "Columbus",
    degree: "PhD",
    specialties: specialties.map(s => s.value).slice(...randomSpecialty()),
    yearsOfExperience: 9,
    phoneNumber: "5556781234",
  },
  {
    firstName: "Amanda",
    lastName: "Hall",
    city: "Fort Worth",
    degree: "MSW",
    specialties: specialties.map(s => s.value).slice(...randomSpecialty()),
    yearsOfExperience: 3,
    phoneNumber: "5559872345",
  },
];

export { advocateData };
